networks:
  minecraft:
    name: minecraft

x-mc: &mc
  image: itzg/minecraft-server
  tty: true
  stdin_open: true
  environment:
    EULA: "TRUE"
  networks:
    - minecraft

services:
  velocity:
    image: endkind/velocity:latest
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
    container_name: endkind-velocity
    volumes:
      - ./velocity:/velocity
    environment:
      - MAX_RAM=1G
    restart: always
    networks:
      - minecraft

  mc-1:
    <<: *mc
    ports:
      - "25566:25565"
    volumes:
      - ./mc-1:/data

  mc-2:
    <<: *mc
    ports:
      - "25567:25565"
    volumes:
      - ./mc-2:/data
