---
- name: Install system dependencies
  apt:
    name:
      - python3
      - python3-pip
      - python3-docker
      - docker.io
      - docker-buildx
      - docker-compose-v2
      - jq
      - rsync
      - nfs-common
      - nfs-kernel-server
      - python3-certbot
      - python3-jsondiff
    update_cache: yes
    state: present

- import_tasks: docker.yml

- import_tasks: users.yml

- import_tasks: ssh.yml
