networks:
  minecraft:
    name: minecraft

x-paper: &paper
  image: docker.io/tonyd33/papermc-docker
  tty: true
  stdin_open: true
  environment:
    EULA: "true"
    MC_VERSION: "1.21.4"
    PAPER_BUILD: "187"
    URL: "https://api.papermc.io/v2/projects/paper"
  networks:
    - minecraft

services:
  velocity:
    image: docker.io/endkind/velocity:latest
    hostname: velocity
    container_name: velocity
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
    volumes:
      - ./velocity:/velocity
    environment:
      - MAX_RAM=1G
    restart: unless-stopped
    networks:
      - minecraft

  paper-1:
    <<: *paper
    hostname: paper-1
    # Disable this when deploying, connections should be made through the
    # velocity proxy.
    ports:
      - 25566:25565
    volumes:
      - ./paper-1:/papermc
    networks:
      - minecraft
